version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    tmpfs:
      - /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "fsync=off" # to increase performance
