server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:15432/backend
    username: backend
    password: backend